name: starter
description: flutter starter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #  상태관리
  flutter_bloc: ^8.1.2

  #  국제화
  intl: ^0.17.0

  # images
  flutter_svg: ^2.0.0+1
  freezed: ^2.3.2
  cached_network_image: ^3.2.3

  #  utility:
  permission_handler: ^10.2.0
  #  라우팅
  go_router: ^6.0.6
  # ui
  flutter_screenutil: ^5.6.1

  #  network
  socket_io_client: ^2.0.1

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  very_good_analysis: ^4.0.0+1
  change_app_package_name: ^1.1.0

  # native splash & launcher icon
  flutter_native_splash: ^2.2.14
  flutter_launcher_icons: ^0.11.0

  #  flutter pub run build_runner build --delete-conflicting-outputs
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  #  fonts:
  #    - family: notoSans
  #      fonts:
  #        - asset: assets/fonts/NotoSansKR-Regular.otf
  #        - asset: assets/fonts/NotoSansKR-Bold.otf
  #          weight: 700
  #
  assets:
    - assets/image/
#    - assets/icons/2x/
#    - assets/icons/3x/
#    - assets/img/
#    - assets/img/2x/
#    - assets/img/3x/

flutter_native_splash:
  color: "#FFFFFF"
  android_gravity: center
  ios_content_mode: center

flutter_icons:
  image_path: "assets/image/launcher_icon.png"
  android: true
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true